#!/usr/bin/env bash
export HOME=/home/c9
export C9USER=c9

if [ -f ${HOME}/dev/server/app.js ]; then
  cd ${HOME}/dev/server
  . $HOME/.nvm/nvm.sh
  exec /sbin/setuser ${C9USER} node app.js
else
  exec sleep infinity
fi

