#!/usr/bin/env bash
export HOME=/home/c9
export C9USER=c9

cd ${HOME}/dev
. ../.nvm/nvm.sh

if [ -f ${HOME}/dev/server.js ]; then
  exec /sbin/setuser ${C9USER} node server.js
else
  exec sleep infinity
fi
